<a href="https://colab.research.google.com/github/Gabrielvitorf6/Data_Science_Univesp_Course/blob/main/COM350_aula05_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 05 Univesp do curso: Introdução a Ciência de Dados

Aula sobre a biblioteca Numpy do Python

In [1]:
import numpy as np

crio um objeto n dimensional com duas listas com três elementos

In [ ]:
dados=np.random.rand(2,3)

In [ ]:
dados

array([[0.11086028, 0.53683603, 0.1127153 ],
       [0.6689939 , 0.92782618, 0.3450978 ]])

Ver o tipo dos dados

In [ ]:
dados.dtype

dtype('float64')

Ver tamanho e quantidade de dimensões

In [ ]:
dados.shape

(2, 3)

In [ ]:
dados.ndim

2

Criar arrays usando o ndarray do Numpy. Ele identifica o tipo do dado do array e cria um array numpy com base em um array do python

In [ ]:
lista = [1,7.1, 2 , 6 , 3,11]

In [ ]:
dados2=np.array(lista)

In [ ]:
dados2

array([ 1. ,  7.1,  2. ,  6. ,  3. , 11. ])

Observamos que ele decide que todos os dados devem ser do tipo float automaticamente. Esse array é do NUMPY, não do Python

In [ ]:
lista2= [[1,2,3,4],[4,3,2,1]]

In [ ]:
dados3=np.array(lista2)

In [ ]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

Ele também cria arrays multidimensionais

Existem várias maneiras de criar arrays no Numpy, como por exemplo criar arrays somente com zeros

In [ ]:
dadoszero=np.zeros(20)

In [ ]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
dadoszeromulti=np.zeros((2,3))

In [ ]:
dadoszeromulti

array([[0., 0., 0.],
       [0., 0., 0.]])

Temos a mesma função com o número um também

In [ ]:
dadosum=np.ones(15)

In [ ]:
dadosum

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
dadosummulti=np.ones((5,5))

In [ ]:
dadosummulti

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Podemos criar arrays de números sequenciais

In [ ]:
dadosseq=np.arange(7)

In [ ]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6])

Criando array de 0 até 50, pulando de dois em dois

In [ ]:
dadosseq2=np.arange(0, 50 , 2)

In [ ]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
dadosseq2.dtype

dtype('int64')

Também podemos transformar o tipo de um dado de maneira explicíta. Usamos essa função em várias situações enquanto estivermos desenvolvendo

In [ ]:
dadosseq3=dadosseq.astype(float)

In [ ]:
dadosseq3.dtype

dtype('float64')

In [ ]:
dadosseq3

array([0., 1., 2., 3., 4., 5., 6.])

O Numpy simplifica muito operações aritméricas com arrays, pois ele permite realizar elas para um ndarray inteiro, ou em módulos específicos dele

> Adicionar aspas



In [ ]:
dados4=np.array([[1,2,3],[4,5,6]])

In [ ]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
dados4*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
dados4/5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [ ]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

Observe que ao realizarmos essas operações aritméticas, não alteramos os valores dos arrays, só obtemos uma visualização dos resultados. Abaixo criamos de fato, um novo array

In [ ]:
dados5= dados4*dados4

In [ ]:
dados5

array([[ 1,  4,  9],
       [16, 25, 36]])

Possos realizar comparações entre os objetos também:

In [ ]:
dados5>dados4

array([[False,  True,  True],
       [ True,  True,  True]])

Indexação em Numpy



Indexação: Localiza um valor dentro de um objeto, através de seu indíce, sendo ele uni dimensional, ou bi dimensional

In [ ]:
# aqui vemos a variável dadoseq
dadosseq

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
dadosseq[5]

np.int64(5)

In [ ]:
dadosseq[3:6]

array([3, 4, 5])

In [ ]:
dadosseq[3:6] = 20

In [ ]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6])

É importante ressaltar que diferente de uma lista Python, um recorte de um ndarray sofrerá broadcast(A mudança será perpetuada para a variável original(nesse caso = dadosseq), ao contrário do exemplo acima das operações aritméticas) - funciona de maneira específica as views de BDs.

In [ ]:
fatiadados = dadosseq[2:4]

In [ ]:
fatiadados
#Observe que começa a retornar os valores no número exato que passamos o começo(indíce 2) mas ele para uma casa antes no número passado para o fim  fim(indíce 4)

array([ 2, 20])

In [ ]:
fatiadados[1] = fatiadados[1] * 2

In [ ]:
fatiadados

array([ 2, 40])

In [ ]:
dadosseq

array([ 0,  1,  2, 40, 20, 20,  6])

In [ ]:
fatiadados[:] = 333

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6])

Copiar dados para evitar o broadcast.
No exemplo abaixo observamos como o método copy evade o broadcast ao CRIAR uma cópia invés de USAR uma fatia, como no exemplo acima

In [ ]:
fatia2=dadosseq[2:4].copy()

In [ ]:
fatia2

array([333, 333])

In [ ]:
fatia2[:]=111

In [ ]:
fatia2

array([111, 111])

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6])

Arrays com mais de uma dimensão

In [ ]:
#Criamos três listas de três posições cada
dados6 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dados6[1,2]

np.int64(6)

In [ ]:
#O número 6 é retornado pois a MESMA lógica dos arrays anteriores de começar as contagens a partir do 0, também é aplicada aqui, então a coluna 1(4,5,6) no índice 2(0,1,2) é igual a 6

Máscaras: Compara valores de um array e gera um NOVO array baseado nisso

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6])

In [ ]:
mascara=(dadosseq<100)

In [ ]:
mascara

array([ True,  True, False, False,  True,  True,  True])

In [ ]:
#Atribuo valores 8888 para todos os valores que estejam presentes no array e que são menores que 20
dadosseq[dadosseq<20] = 8888

In [ ]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888])

Transposição

In [ ]:
#Crio array 15 dígitos sequenciais(começando a contar do 0) com 3 listas de 5 posições cada
dados7 = np.arange(15).reshape(3,5)

In [ ]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Com o método .T do ndarray, faço uma transposição e inverto a matriz de lado

In [ ]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Multiplicação de Matrizes com Dots

In [ ]:
np.dot(dados7.T,2 )

array([[ 0, 10, 20],
       [ 2, 12, 22],
       [ 4, 14, 24],
       [ 6, 16, 26],
       [ 8, 18, 28]])

In [ ]:
np.dot(dados7.T, dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])